# gz topic published by the simulator core
- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# gz topic published by IMU plugin
- ros_topic_name: "imu"
  gz_topic_name: "imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

# Navsat_gpsfix configuration.
# - topic_name: "/navsat"
- ros_topic_name: "gps/fix"
  gz_topic_name: "gps/fix"
  # ros_type_name: "gps_msgs/msg/GPSFix"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  gz_type_name: "gz.msgs.NavSat"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (Lidar)
- ros_topic_name: "scan"
  gz_topic_name: "scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (Left Camera)
- ros_topic_name: "left_camera/camera_info"
  gz_topic_name: "left_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (Right Camera)
- ros_topic_name: "right_camera/camera_info"
  gz_topic_name: "right_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (Center ZED Camera)
- ros_topic_name: "right_camera/camera_info"
  gz_topic_name: "right_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# gz topic published for Sensors plugin (ZED depth camera info)
- ros_topic_name: "rgbd_camera/camera_info"
  gz_topic_name: "rgbd_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  # lazy: true
  direction: GZ_TO_ROS

# gz topic published for Sensors plugin (ZED depth camera image)
- ros_topic_name: "/rgbd_camera/depth_image"
  gz_topic_name: "/rgbd_camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  # lazy: true
  direction: GZ_TO_ROS

# gz topic published for Sensors plugin (ZED depth camera point cloud)
- ros_topic_name: "/rgbd_camera/points"
  gz_topic_name: "/rgbd_camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  # lazy: true
  direction: GZ_TO_ROS
